#!/usr/bin/env bash
#  ____           _           _ 
# |  _ \    ___  (_) __   __ (_)	David González (deivi)
# | | | |  / _ \ | | \ \ / / | |  github.com/deivi98
# | |_| | |  __/ | |  \ V /  | |  
# |____/   \___| |_|   \_/   |_|
#


# Declaring a cool nice looking error function
error() {
  printf "\e[31m┌────────────────────────────┤ ERROR ├────────────────────────────┐\n"

  readarray -t arr < <(fold -w63 <<< "$1")

  for i in "${arr[@]}"
  do
    printf "│\e[0m %-63s \e[31m│\n" "$i"
  done

  printf "\e[31m└─────────────────────────────────────────────────────────────────┘\n"
  exit 1
}

info() {
  printf "\e[33m[INFO]\e[0m $1\n" 
}

success() {
  printf "\e[32m[SUCCESS]\e[0m $1\n" 
}



# Checking that user is not root
if [ "$(id -u)" = 0 ]; then
    error "This script cannot be run as root user since it makes changes to your \$HOME directory. You will be asked for a sudo password when neccessary."
fi


info "Syncing repos..."
sudo pacman --noconfirm --needed -Syu || error "Error when syncing the repos."
sucess "Repos synced"

SCRIPT_DEPENDENCIES="dialog grep sed"
info "Installing script dependencies..."
sudo pacman --noconfirm --needed -Syu $SCRIPT_DEPENDENCIES || error "Error installing script dependencies."
success "Script dependencies installed"

# Welcome dialog
dialog --colors --title "ARCHAOS Welcome" --msgbox "Welcome to ARCHAOS post installation script. It deploys my personal set of packages, apps and dotfiles. ARCHAOS should work on Arch Linux or any x64 Arch-based distribution." 10 60
clear

# Acknowledgement
info "Asking user for acknowledgement"
dialog --colors --title "Acknowledgement" --yes-label "Continue" --no-label "Exit" --yesno "By running this script you acknowledge you are entirely responsible for the impact it could have in your machine. This script is design to be executed in a virgin Arch-based OS as a post installation. It could delete/overwrite your personal config files otherwise. Please use at your own risk." 10 60 || { clear; exit 1; }
clear
success "Acknowledgement done"
# Summary
dialog --colors --title "Installation" --yes-label "Begin installation" --no-label "Cancel" --yesno "The following steps will be followed:\n1. Install packages\n2. Install Yay\n3. Install AUR Packages\n4. Install editor (Lunar Vim)\n5. Clone and install dotfiles\n6. Install additional apps" 13 60 || { clear; exit 1; }
clear
info "Begining installation..."

# Extract all official packages from archaos.pkgs file
packagelist=$(cat archaos.pkgs | grep -v -e '^$' | grep -v "#" | grep -v "AUR/")

# Preview all packages to install
dialog --colors --title "Install packages" --yes-label "Install" --no-label "Exit" --yesno "The following packages will be installed from the official Arch repos:\n\n$packagelist" 15 80 || { clear; exit 1; }

# Install packages
info "Installing packages..."
sudo pacman --needed --ask 4 -Sy $packagelist || error "Error when installing packages, please check the output log"
success "Packages installed"

# Install yay
info "Installing yay..."
git clone https://aur.archlinux.org/yay.git ~/yay && cd ~/yay && makepkg -si --needed --noconfirm && cd ~/archaos && rm -rf ~/yay || error "Error when installing Yay."
success "Yay installed"


# Extract all AUR packages from archaos.pkgs file
aurpackagelist=$(cat archaos.pkgs | grep -v -e '^$' | grep -v "#" | grep AUR/ | sed --expression='s/AUR\///g')

# Preview all packages to install
dialog --colors --title "Install AUR packages" --yes-label "Install" --no-label "Exit" --yesno "The following packages will be installed from the AUR repos:\n\n$aurpackagelist" 15 80 || { clear; exit 1; }

# Install AUR packages
info "Installing AUR packages..."
yay --needed --noconfirm -Sy $aurpackagelist || error "Error when installing AUR packages, please check the output log"
success "AUR packages installed"

info "Asking user to install Lunar Vim..."
# Ask for confirmation
if dialog --colors --title "Install editor (Lunar Vim)" --yes-label "Yes, install" --no-label "No, skip" --yesno "Do you want to install Lunar Vim as editor? Lunar Vim is an extensive configuration of Neovim.\n\nMore can be found at https://www.lunarvim.org/" 10 60; then

  info "Installing Lunar Vim..."
  # Lunar Vim dependencies
  info "Intalling Lunar Vim dependencies..."
  sudo pacman --needed --ask 4 -Sy neovim nodejs npm python-pip cargo || error "Error installing Lunar Vim dependencies."
  sucess "Lunar Vim dependencies installed"

  # Lunar Vim installation script
  info "Running Lunar Vim installation script..."
  export npm_config_prefix="$HOME/.local"
  curl https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh | bash -s -- --yes --overwrite || error "Error installing Lunar Vim, please check the output"
  success "Lunar Vim installed"
else
  info "Skipping Lunar Vim installation"
fi

if dialog --colors --title "Clone and install dotfiles" --yes-label "Install" --no-label "No, skip" --yesno "Do you want to clone and install Deivi's dotfiles? They will be downloaded and copied into your home directory.\n\nMore about them at https://github.com/deivi98/dotfiles" 10 60; then
  info "Installing dotfiles..."

  info "Creating .config backup"
  [ -d ~/.config ] && mkdir ~/.config-backup-$(date +%Y.%m.%d-%H%M) && cp -Rf ~/.config ~/.config-backup-$(date +%Y.%m.%d-%H%M)
  [ ! -d ~/.config ] && mkdir ~/.config

  info "Cloning dotfiles repo"
  [ ! -d ~/.config/dotfiles ] && git clone --bare https://github.com/deivi98/dotfiles ~/.config/dotfiles

  git --git-dir=$HOME/.config/dotfiles/ --work-tree=$HOME config --local status.showUntrackedFiles no

  info "Copying dotfiles into home directory"
  git --git-dir=$HOME/.config/dotfiles/ --work-tree=$HOME checkout -f

  info "Making scripts executable"
  [ -d ~/.config/scripts ] && chmod -R +x ~/.config/scripts
  [ -d ~/.local/bin ] && chmod -R +x ~/.local/bin

  success "Dotfiles installed"
else
  info "Skipping dotfiles installation"
fi



# Prepares sections and packages
gaming_kernel="linux-zen linux-zen-headers"
nvidia_drivers="nvidia nvidia-utils lib32-nvidia-utils nvidia-settings"
redshift="redshift"
bluetooth="bluez bluez-utils"
peripherals="libratbag piper"

result=(dialog --colors --title "Additional packages" --separate-output --ok-label "Install" --cancel-label "No, skip" --checklist "Some packages you might be interested in installing" 0 0 0)

# Builds packages into options
options=("$gaming_kernel" "Gaming kernel" off 
  "$nvidia_drivers" "Nvidia drivers" off
  "$redshift" "Eye caring" off
  "$bluetooth" "Bluetooth" off
  "$peripherals" "Peripherals" off)

# Prompts dialog to user
selections=$("${result[@]}" "${options[@]}" 2>&1 >/dev/tty)
clear

# Install selections
info "Installing additional packages..."
[[ ! -z "$selections" ]] && sudo pacman --needed --noconfirm -Sy $selections || error "Error installing additional packages."
success "Additional packages installed"


result=(dialog --colors --title "Additional apps" --separate-output --ok-label "Install" --cancel-label "No, skip" --checklist "Some apps you might want to install" 0 0 0)

# Builds packages into options
options=("nextcloud-client" "Nextcloud Sync" off 
  "telegram-desktop" "Telegram" off
  "discord" "Discord" off
  "steam" "Steam" off
  "transmission-gtk" "Torrent downloader" off
  "virtualbox virtualbox-host-dkms" "Virtual Box" off)

# Prompts dialog to user
selections=$("${result[@]}" "${options[@]}" 2>&1 >/dev/tty)
clear

# Install selections
info "Installing additional apps..."
[[ ! -z "$selections" ]] && sudo pacman --needed --noconfirm -Sy $selections || error "Error installing additional apps."
success "Additional apps installed"


result=(dialog --colors --title "Additional AUR apps" --separate-output --ok-label "Install" --cancel-label "No, skip" --checklist "Some apps are available just in the AUR repos, pick the ones you want to install" 0 0 0)

# Builds packages into options
options=("mailspring" "Mail client" off 
  "plex-media-player" "Plex TV" off
  "srain" "IRC client" off
  "proton" "Steam wine emulator" off
  "spigot" "Minecraft server" off
  "minecraft-launcher" "Minecraft" off)

# Prompts dialog to user
selections=$("${result[@]}" "${options[@]}" 2>&1 >/dev/tty)
clear

# Install selections
info "Installing additional AUR apps..."
[[ ! -z "$selections" ]] && yay --needed --noconfirm -Sy $selections || error "Error installing additional AUR apps."
success "Additional AUR apps installed"

if dialog --colors --title "Installation complete" --yes-label "Reboot" --no-label "No, skip" --yesno "Congratulations! ARCHAOS has been installed in your system. Enjoy! :)" 10 60; then
  reboot
else
  clear
  exit 0
fi
